### PR TITLE
Modified Jmeter rest requests

### PR DESCRIPTION
**Pull request by spathare21**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-performance/7)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
@spathare21 did this change how the header's jmeter parameters work?

**Comment by spathare21** [comment]
@djansen-redhat I have passed those parameters through user defined variable. so that it take prams from cmd. and if we have to hard code the values just needs to update it in user defined variable.

**Comment by djansen-redhat** [comment]
@spathare21 ok, that sounds likely better.

**Review by djansen-redhat — APPROVED** [review]
Looks good to me. It would be good to see a result set soon, even if it's from just a basic-yet-stable environment.

**Pull request merged**
