### PR TITLE
JMeter performance test product and verification

### PR DESCRIPTION
**Pull request by djansen-redhat**
Tests and scripts for executing performance evaluation on
a T510 ThinkPad.

### CODE REVIEW

**Comment by carlosmunoz** [comment]
@djansen-redhat not sure I'm the right person to review this

**Comment by seanf** [comment]
As discussed in person, ideally we would either have a script which runs after jmeter to evaluate the aggregate results, perhaps comparing the 90% line for each sample against a target duration, or, if possible, get the Jenkins plugin to do a similar evaluation against the duration from the previous build.

**Comment by djansen-redhat** [comment]
@seanf updated with new script, readme and jmx with values in the label (you don't need to review the latter)

**Comment by seanf** [comment]
:+1: Looks good, but I wouldn't bother keeping aggregate390.csv.

**Comment by djansen-redhat** [comment]
Done.

**Comment by djansen-redhat** [comment]
Testing on Jenkins before merge...

**Pull request merged**
