### PR TITLE
Basic memory test for idle Zanata server

### PR DESCRIPTION
**Pull request by djansen-redhat**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-performance/6)

### CODE REVIEW

**Comment by alex-sl-eng** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

_[MemoryTest.groovy, line 30 at r1](https://reviewable.io:443/reviews/zanata/zanata-performance/6#-KRjkoerep1zDs_mK9lQ:-KRjkoerep1zDs_mK9lR:br0nbot) ([raw file](https://github.com/zanata/zanata-performance/blob/2e1a9fe5e42391139296bd1d0cbf0f167d597d5c/MemoryTest.groovy#L30)):_

> ``` Groovy
> void parseOpts(args) {
>     infoOut "Parsing options"
>     def cli = new CliBuilder(usage:'memory_test.py [-h -v -i <interval> -p <processid> -c <count> -t <threshold>]')
> ```

.py? or .groovy?

---

_[MemoryTest.groovy, line 38 at r1](https://reviewable.io:443/reviews/zanata/zanata-performance/6#-KRjl3xHbMC3LcX7_0ME:-KRjl3xHbMC3LcX7_0MF:br1is68) ([raw file](https://github.com/zanata/zanata-performance/blob/2e1a9fe5e42391139296bd1d0cbf0f167d597d5c/MemoryTest.groovy#L38)):_

> ``` Groovy
>         p longOpt: 'processid', args:1, argName:'process', "ID of Zanata server process, eg. 123456"
>         t longOpt: 'threshold', args:1, argName:'thresholdMultiplier', "Max memory increase (multiplied) before failure [1.1]"
>         s longOpt: 'startmem', args:1, argName:'startmem', "Starting memory (for script testing)"
> ```

not sure if we need to stick with camelcase for all these opt?

---

_[MemoryTest.groovy, line 44 at r1](https://reviewable.io:443/reviews/zanata/zanata-performance/6#-KRjlPcqh-hfhQq_0JFu:-KRjlPcryuSMH2CaMKMp:b-whyuat) ([raw file](https://github.com/zanata/zanata-performance/blob/2e1a9fe5e42391139296bd1d0cbf0f167d597d5c/MemoryTest.groovy#L44)):_

> ``` Groovy
>         return
>     }
>     if (options.h) {
> ```

Can we use switch to handle lots of if-else statement?

---

_[MemoryTest.groovy, line 71 at r1](https://reviewable.io:443/reviews/zanata/zanata-performance/6#-KRjlhFy8zh1u-L_pN2g:-KRjlhFzGiuL97TN6fvX:b-ifvksk) ([raw file](https://github.com/zanata/zanata-performance/blob/2e1a9fe5e42391139296bd1d0cbf0f167d597d5c/MemoryTest.groovy#L71)):_

> ``` Groovy
>  * Exit with failure
>  */
> void gameOver(message) {
> ```

ahahahaha, I like gameOver, but for the sake of others which prefer more readability, we might need to rename this method

---

_[MemoryTest.groovy, line 183 at r1](https://reviewable.io:443/reviews/zanata/zanata-performance/6#-KRjmj4kR1QPhlwXhlj2:-KRjmj4kR1QPhlwXhlj3:blrd2qb) ([raw file](https://github.com/zanata/zanata-performance/blob/2e1a9fe5e42391139296bd1d0cbf0f167d597d5c/MemoryTest.groovy#L183)):_

> ``` Groovy
> 
>     // Begin sampling
>     1.upto(count, {
> ```

Do we also display out detailed memory usage over every seconds or minutes depending on the interval set?

---

_[README.md, line 29 at r1](https://reviewable.io:443/reviews/zanata/zanata-performance/6#-KRjjwY4T81PPBpuCduP:-KRjjwY4T81PPBpuCduQ:b-a1wnkz) ([raw file](https://github.com/zanata/zanata-performance/blob/2e1a9fe5e42391139296bd1d0cbf0f167d597d5c/README.md#L29)):_

> ``` Markdown
> ### MemoryTest
> ```
> 
> memory_test.py [-h -v -i <interval> -p <processid> -c <count> -t <threshold> -s <startingMemory>]
> 
> ```
> ```

Do we still have the .py version?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-performance/6)_

**Comment by djansen-redhat** [comment]
_[MemoryTest.groovy, line 30 at r1](https://reviewable.io:443/reviews/zanata/zanata-performance/6#-KRjkoerep1zDs_mK9lQ:-KRkS0vhOmSN5yiNmZJd:b-834n6i) ([raw file](https://github.com/zanata/zanata-performance/blob/2e1a9fe5e42391139296bd1d0cbf0f167d597d5c/MemoryTest.groovy#L30)):_
<details><summary>

<i>Previously, aeng (Alex Eng) wrote…</i></summary>



> .py? or .groovy?
> </details>
> Oops.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-performance/6)_

**Comment by djansen-redhat** [comment]
_[MemoryTest.groovy, line 38 at r1](https://reviewable.io:443/reviews/zanata/zanata-performance/6#-KRjl3xHbMC3LcX7_0ME:-KRkSDi73HxT6wx5LpLV:bcwmvf2) ([raw file](https://github.com/zanata/zanata-performance/blob/2e1a9fe5e42391139296bd1d0cbf0f167d597d5c/MemoryTest.groovy#L38)):_
<details><summary>

<i>Previously, aeng (Alex Eng) wrote…</i></summary>



> not sure if we need to stick with camelcase for all these opt?
> </details>
> I don't know either, but I'll do it. I've seen so many variations.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-performance/6)_

**Comment by djansen-redhat** [comment]
_[MemoryTest.groovy, line 44 at r1](https://reviewable.io:443/reviews/zanata/zanata-performance/6#-KRjlPcqh-hfhQq_0JFu:-KRkSL7XI9Jxq83xXy1p:brn4tvi) ([raw file](https://github.com/zanata/zanata-performance/blob/2e1a9fe5e42391139296bd1d0cbf0f167d597d5c/MemoryTest.groovy#L44)):_
<details><summary>

<i>Previously, aeng (Alex Eng) wrote…</i></summary>



> Can we use switch to handle lots of if-else statement?
> </details>
> After a bit of discussion, they're not actually else's - which would make it difficult to code in a switch without clunkiness.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-performance/6)_

**Comment by djansen-redhat** [comment]
_[MemoryTest.groovy, line 71 at r1](https://reviewable.io:443/reviews/zanata/zanata-performance/6#-KRjlhFy8zh1u-L_pN2g:-KRkSaLm4O4Ckj4lmpKL:br9uhv6) ([raw file](https://github.com/zanata/zanata-performance/blob/2e1a9fe5e42391139296bd1d0cbf0f167d597d5c/MemoryTest.groovy#L71)):_
<details><summary>

<i>Previously, aeng (Alex Eng) wrote…</i></summary>



> ahahahaha, I like gameOver, but for the sake of others which prefer more readability, we might need to rename this method
> </details>
> Booooo

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-performance/6)_

**Comment by djansen-redhat** [comment]
_[MemoryTest.groovy, line 183 at r1](https://reviewable.io:443/reviews/zanata/zanata-performance/6#-KRjmj4kR1QPhlwXhlj2:-KRkSeuwU0ww_eq2_4hD:b-8hgco4) ([raw file](https://github.com/zanata/zanata-performance/blob/2e1a9fe5e42391139296bd1d0cbf0f167d597d5c/MemoryTest.groovy#L183)):_
<details><summary>

<i>Previously, aeng (Alex Eng) wrote…</i></summary>



> Do we also display out detailed memory usage over every seconds or minutes depending on the interval set?
> </details>
> Yes, every time the interval ticks.  The interval is actually built into pidstat, as a sort of 'wait' before reading.  The test will fail on the first interval that exceeds the threshold, but will save the warning for a smaller memory increase.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-performance/6)_

**Comment by djansen-redhat** [comment]
_[README.md, line 29 at r1](https://reviewable.io:443/reviews/zanata/zanata-performance/6#-KRjjwY4T81PPBpuCduP:-KRkT4Y8bovcHTZNs8Yl:b2ni9es) ([raw file](https://github.com/zanata/zanata-performance/blob/2e1a9fe5e42391139296bd1d0cbf0f167d597d5c/README.md#L29)):_
<details><summary>

<i>Previously, aeng (Alex Eng) wrote…</i></summary>



> Do we still have the .py version?
> </details>
> omg

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-performance/6)_

**Comment by alex-sl-eng** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-performance/6#-:-KSYzKn5AEvDoVMJmnS-:bnfp4nl)_

**Pull request merged**
